include:
  - board: corneish_zen_v2_left
    snippet: studio-rpc-usb-uart
  - board: corneish_zen_v2_right
  - board: corneish_zen_v2_left
    shield: settings_reset
  - board: corneish_zen_v2_right
    shield: settings_reset
